name: Run Jest

on:
  push:
    branches:
      - '**'

jobs:
  run-jest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run Jest
        run: npm run test

      - name: Clean up
        run: |
          ls -la ./
          rm -rf ./*

      - name: Clear cache of npm
        run: npm cache clean --force
